---
driver:
  name: vagrant
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['https_proxy'] %>
  no_proxy: <%= ENV['no_proxy'] %>

provisioner:
  name: chef_zero
  client_rb:
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['https_proxy'] %>
    no_proxy: <%= ENV['no_proxy'] %>
    ssl_verify_mode: :verify_none
    verify_api_cert: false

platforms:
  - name: oel-6.6
    driver_config:
      box: oel66

suites:
  - name: default
    run_list:
      - recipe[oel_pkg_test::default]
